# Generated by Django 3.2.5 on 2021-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formtypechoicesmodel',
            options={'ordering': ('title', 'id')},
        ),
        migrations.AddField(
            model_name='studentforms',
            name='status',
            field=models.CharField(choices=[('Used', 'used'), ('Expired', 'expired'), ('New', 'new')], default='New', max_length=30),
        ),
    ]
