# Generated by Django 3.2.5 on 2021-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20211017_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesofadmissionforms',
            options={'verbose_name_plural': 'Sales of Admission Forms'},
        ),
        migrations.AlterModelOptions(
            name='studentforms',
            options={'verbose_name_plural': 'Student Forms'},
        ),
        migrations.AddField(
            model_name='formtypechoicesmodel',
            name='subtitle',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
