# Generated by Django 3.2.5 on 2021-10-18 07:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20211017_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentforms',
            name='academic_year',
            field=models.CharField(help_text='this_year / next_year', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='candidate_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='candidate_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='sales_agent',
            field=models.CharField(max_length=120, null=True, verbose_name="Sales agent's"),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='sales_point',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='sales_point_location',
            field=models.CharField(help_text='Town, city or community', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='status',
            field=models.CharField(choices=[('Used', 'used'), ('In use', 'in use'), ('Expired', 'expired'), ('New', 'new')], default='New', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
