# Generated by Django 3.2.5 on 2021-10-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20211018_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentforms',
            name='status',
            field=models.CharField(choices=[('Completed', 'completed'), ('At Profile', 'at profile'), ('At Address', 'at address'), ('At Certification', 'at certification'), ('Expired', 'expired'), ('New', 'new')], default='New', max_length=30, null=True),
        ),
    ]
