# Generated by Django 3.2.5 on 2021-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_studentforms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentforms',
            name='serial_number',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentforms',
            unique_together=set(),
        ),
    ]
