# Generated by Django 3.2.5 on 2021-10-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20211019_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentforms',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('at profile', 'At Profile'), ('at address', 'At Address'), ('at certification', 'At Certification'), ('at employment', 'At Employment History'), ('expired', 'Expired'), ('new', 'New')], default='new', max_length=30, null=True),
        ),
    ]
