# Generated by Django 3.2.5 on 2021-10-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_alter_studentforms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentforms',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('at profile', 'At Profile'), ('at address', 'At Address'), ('at certification', 'At Certification'), ('at employment', 'At Employment History'), ('at sponsor', 'AT SPONSORSHIP'), ('at programme', 'AT PROGRAMME'), ('at education', 'AT EDUCATION'), ('expired', 'Expired'), ('new', 'New')], default='new', max_length=30, null=True),
        ),
    ]
