# Generated by Django 3.2.5 on 2021-11-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_auto_20211104_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentforms',
            name='academic_year',
            field=models.CharField(choices=[('1999/2000', '1999/2000'), ('2000/2001', '2000/2001'), ('2001/2002', '2001/2002'), ('2002/2003', '2002/2003'), ('2003/2004', '2003/2004'), ('2004/2005', '2004/2005'), ('2005/2006', '2005/2006'), ('2006/2007', '2006/2007'), ('2007/2008', '2007/2008'), ('2008/2009', '2008/2009'), ('2009/2010', '2009/2010'), ('2010/2011', '2010/2011'), ('2011/2012', '2011/2012'), ('2012/2013', '2012/2013'), ('2013/2014', '2013/2014'), ('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020')], default=(2020, 2021), help_text='this_year / next_year', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('submitted', 'Submitted'), ('at profile', 'At Profile'), ('at address', 'At Address'), ('at certification', 'At Certification'), ('at employment', 'At Employment History'), ('at sponsor', 'AT SPONSORSHIP'), ('at programme', 'AT PROGRAMME'), ('at education', 'AT EDUCATION'), ('expired', 'Expired'), ('new', 'New'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=30, null=True),
        ),
    ]
