# Generated by Django 3.2.5 on 2021-11-08 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20211104_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentforms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 8, 16, 59, 19, 449216, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
