# Generated by Django 3.2.5 on 2021-11-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_auto_20211108_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentforms',
            options={'permissions': [('can_audit_admission_form', 'can audit student admission form')], 'verbose_name_plural': 'Student Forms'},
        ),
    ]
