# Generated by Django 3.2.9 on 2021-11-21 15:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_auto_20211121_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentforms',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2020/2021', '2020/2021'), ('2019/2020', '2019/2020'), ('2018/2019', '2018/2019'), ('2017/2018', '2017/2018'), ('2016/2017', '2016/2017'), ('2015/2016', '2015/2016'), ('2014/2015', '2014/2015'), ('2013/2014', '2013/2014'), ('2012/2013', '2012/2013'), ('2011/2012', '2011/2012'), ('2010/2011', '2010/2011'), ('2009/2010', '2009/2010'), ('2008/2009', '2008/2009'), ('2007/2008', '2007/2008'), ('2006/2007', '2006/2007'), ('2005/2006', '2005/2006'), ('2004/2005', '2004/2005'), ('2003/2004', '2003/2004'), ('2002/2003', '2002/2003'), ('2001/2002', '2001/2002'), ('2000/2001', '2000/2001')], default=(2020, 2021), help_text='this_year / next_year', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='candidate_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='cost',
            field=models.IntegerField(blank=True, help_text='Current in Ghana Cedis', null=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='sales_agent',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="Sales agent's"),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='sales_point',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='sales_point_location',
            field=models.CharField(blank=True, help_text='Town, city or community', max_length=120, null=True),
        ),
    ]
