# Generated by Django 3.2.9 on 2021-11-22 14:14

import CollegeManagementSystem.validation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0016_alter_studentforms_candidate_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentforms',
            options={'permissions': [('can_audit_admission_form', 'can audit student admission form'), ('can_reject_studentform', 'can reject student admission form'), ('can_accept_studentform', 'can accept student admission form'), ('view_studentform_detail', 'view student admission form detail')], 'verbose_name_plural': 'Student Forms'},
        ),
        migrations.AlterField(
            model_name='formtypechoicesmodel',
            name='subtitle',
            field=models.CharField(max_length=120, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
        migrations.AlterField(
            model_name='formtypechoicesmodel',
            name='title',
            field=models.CharField(max_length=120, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
        migrations.AlterField(
            model_name='studentforms',
            name='form_type',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='admission.formtypechoicesmodel'),
        ),
        migrations.AddConstraint(
            model_name='formtypechoicesmodel',
            constraint=models.UniqueConstraint(fields=('title', 'subtitle'), name='unique_formtype'),
        ),
    ]
