# Generated by Django 3.2.9 on 2021-11-23 11:25

import CollegeManagementSystem.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Semester/term name. Eg. First Semester', max_length=60, unique=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space])),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'institution_semester',
            },
        ),
    ]
