# Generated by Django 3.2.9 on 2021-11-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_semestermodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestermodel',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='semestermodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_active_semester'),
        ),
    ]
