# Generated by Django 3.2.9 on 2021-11-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_programme_max_student'),
        ('system', '0004_auto_20211124_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevelTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.IntegerField(help_text='Current number of student')),
                ('max_number', models.IntegerField(help_text='Maximum number of student')),
                ('academic_year', models.CharField(choices=[('2020/2021', '2020/2021'), ('2019/2020', '2019/2020'), ('2018/2019', '2018/2019'), ('2017/2018', '2017/2018'), ('2016/2017', '2016/2017'), ('2015/2016', '2015/2016'), ('2014/2015', '2014/2015'), ('2013/2014', '2013/2014'), ('2012/2013', '2012/2013'), ('2011/2012', '2011/2012'), ('2010/2011', '2010/2011'), ('2009/2010', '2009/2010'), ('2008/2009', '2008/2009'), ('2007/2008', '2007/2008'), ('2006/2007', '2006/2007'), ('2005/2006', '2005/2006'), ('2004/2005', '2004/2005'), ('2003/2004', '2003/2004'), ('2002/2003', '2002/2003'), ('2001/2002', '2001/2002'), ('2000/2001', '2000/2001')], default=(2020, 2021), max_length=10)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lvl_total', to='programme.programme')),
            ],
            options={
                'db_table': 'studentleveltotal',
                'order_with_respect_to': 'programme',
            },
        ),
    ]
