# Generated by Django 4.0 on 2022-02-21 11:41

import CollegeManagementSystem.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20211208_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterAcademicYearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Semester/term name. Eg. First Semester', max_length=60, unique=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=False, verbose_name='Current Semester')),
                ('academic_year', models.CharField(choices=[('2021/2022', '2021/2022'), ('2020/2021', '2020/2021'), ('2019/2020', '2019/2020'), ('2018/2019', '2018/2019'), ('2017/2018', '2017/2018'), ('2016/2017', '2016/2017'), ('2015/2016', '2015/2016'), ('2014/2015', '2014/2015'), ('2013/2014', '2013/2014'), ('2012/2013', '2012/2013'), ('2011/2012', '2011/2012'), ('2010/2011', '2010/2011'), ('2009/2010', '2009/2010'), ('2008/2009', '2008/2009'), ('2007/2008', '2007/2008'), ('2006/2007', '2006/2007'), ('2005/2006', '2005/2006'), ('2004/2005', '2004/2005'), ('2003/2004', '2003/2004'), ('2002/2003', '2002/2003'), ('2001/2002', '2001/2002'), ('2000/2001', '2000/2001')], default='2021/2022', max_length=10)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'SemesterAcademicYear',
            },
        ),
    ]
