# Generated by Django 4.0 on 2022-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_semester'),
        ('system', '0008_semesteracademicyearmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemesterModel',
        ),
        migrations.DeleteModel(
            name='System',
        ),
        migrations.AlterField(
            model_name='studentleveltotal',
            name='academic_year',
            field=models.CharField(choices=[('2021/2022', '2021/2022'), ('2020/2021', '2020/2021'), ('2019/2020', '2019/2020'), ('2018/2019', '2018/2019'), ('2017/2018', '2017/2018'), ('2016/2017', '2016/2017'), ('2015/2016', '2015/2016'), ('2014/2015', '2014/2015'), ('2013/2014', '2013/2014'), ('2012/2013', '2012/2013'), ('2011/2012', '2011/2012'), ('2010/2011', '2010/2011'), ('2009/2010', '2009/2010'), ('2008/2009', '2008/2009'), ('2007/2008', '2007/2008'), ('2006/2007', '2006/2007'), ('2005/2006', '2005/2006'), ('2004/2005', '2004/2005'), ('2003/2004', '2003/2004'), ('2002/2003', '2002/2003'), ('2001/2002', '2001/2002'), ('2000/2001', '2000/2001')], default='2021/2022', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='semesteracademicyearmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_active_semester'),
        ),
    ]
