# Generated by Django 4.0 on 2022-02-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_delete_semestermodel_delete_system_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesteracademicyearmodel',
            options={'verbose_name': 'Semesters and Academic Year', 'verbose_name_plural': 'Semesters and Academic Year'},
        ),
    ]
