# Generated by Django 4.0 on 2022-02-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_semesteracademicyearmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesteracademicyearmodel',
            options={'permissions': [('can_student_view_semester_and_academic_year', 'Can student view semester and Academic Year')], 'verbose_name': 'Semesters and Academic Year', 'verbose_name_plural': 'Semesters and Academic Year'},
        ),
    ]
