# Generated by Django 3.2.5 on 2021-10-21 07:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0008_alter_studentforms_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of sponsor or company', max_length=120, verbose_name='Sponsor / Company')),
                ('email', models.EmailField(help_text="Sponsor's email address", max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Sponsor's phone number", max_length=128, null=True, region=None)),
                ('city', models.CharField(blank=True, help_text="Sponsor's city", max_length=120, null=True)),
                ('state', models.CharField(blank=True, help_text="Sponsor's state", max_length=120, null=True)),
                ('address', models.CharField(help_text='Address of sponsor', max_length=120)),
                ('relationship', models.CharField(help_text='Your relationship with the sponsor', max_length=120, null=True)),
                ('scholarship', models.BooleanField()),
                ('on_government_support', models.BooleanField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_sponsored', to='admission.studentforms')),
            ],
            options={
                'verbose_name': 'Student Sponsor',
                'verbose_name_plural': 'Student Sponsors',
                'db_table': 'studentSponsor',
            },
        ),
    ]
