# Generated by Django 3.2.5 on 2021-10-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='on_government_support',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='scholarship',
            field=models.BooleanField(null=True),
        ),
    ]
