# Generated by Django 3.2.5 on 2021-10-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('sponsor', '0002_auto_20211021_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_sponsored', to='student.student'),
        ),
    ]
