# Generated by Django 3.2.9 on 2021-11-24 08:18

import CollegeManagementSystem.validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme', '0003_alter_programme_name'),
        ('system', '0004_auto_20211124_0818'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space])),
                ('code', models.CharField(max_length=30, unique=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_level', to='system.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_programme', to='programme.programme')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_semester', to='system.semestermodel')),
            ],
        ),
    ]
