# Generated by Django 3.2.9 on 2021-11-24 22:41

import CollegeManagementSystem.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211124_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course Code', max_length=30, unique=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='course',
            order_with_respect_to='programme',
        ),
    ]
