# Generated by Django 3.2.9 on 2021-12-11 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20211211_0121'),
        ('course', '0003_auto_20211124_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lecturer', to='lecture.lecturer'),
        ),
    ]
