# Generated by Django 4.0.2 on 2022-03-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('view_courses_list', 'view courses list')]},
        ),
    ]
