# Generated by Django 4.0.2 on 2022-03-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='course',
            order_with_respect_to=None,
        ),
    ]
