# Generated by Django 4.0.2 on 2022-03-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_courseassignment_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_tutor', True)), fields=('lecturer', 'course'), name='unique_course_tutor'),
        ),
    ]
