# Generated by Django 4.0.2 on 2022-03-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_alter_lecturer_profile'),
        ('course', '0011_courseassignment_unique_course_tutor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseassignment',
            name='unique_course_tutor',
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course', 'lecturer'), ('course', 'lecturer', 'is_tutor')},
        ),
    ]
