# Generated by Django 4.0.2 on 2022-03-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_courseassignment_unique_course_tutor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_tutor', True)), fields=('lecturer', 'course', 'is_tutor'), name='unique_course_tutor'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('course', 'lecturer'), name='unique_course_lecturer'),
        ),
    ]
