# Generated by Django 4.0.2 on 2022-03-24 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_courseassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('view_courses_list', 'view courses list'), ('view_lecturer_details', 'Can lecturer view their course details')]},
        ),
    ]
