# Generated by Django 4.0.2 on 2022-05-02 15:03

import course.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='courseassignment',
            managers=[
                ('lecturer_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.upload_course_picture_path),
        ),
    ]
