# Generated by Django 3.2.9 on 2021-12-08 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empoymentHistory', '0005_alter_employmenthistorymodel_employee'),
        ('department', '0004_alter_department_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(help_text='Lecturer identity', max_length=30, unique=True)),
                ('application_letter', models.FileField(help_text='Application/Résumé letter in pdf format', null=True, upload_to='')),
                ('cv', models.FileField(help_text='Lecturers application Curriculum Vitae (CV)', null=True, upload_to='')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('emploment_history', models.ManyToManyField(to='empoymentHistory.EmploymentHistoryModel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
            },
        ),
    ]
