# Generated by Django 3.2.9 on 2021-12-11 01:21

from django.db import migrations, models
import lecture.models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_alter_lecturer_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={'permissions': [('assign_department', 'Assign Department'), ('list_lecturer', 'view lecturers list')], 'verbose_name': 'Lecturer', 'verbose_name_plural': 'Lecturers'},
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='emploment_history',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='application_letter',
            field=models.FileField(help_text='Application/Résumé letter in pdf format', null=True, upload_to=lecture.models.upload_application_letter),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='cv',
            field=models.FileField(help_text='Lecturers application Curriculum Vitae (CV) in pdf format', null=True, upload_to='', verbose_name='Curriculum Vitae (CV)'),
        ),
    ]
