# Generated by Django 4.0.2 on 2022-03-03 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0007_alter_lecturer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='profile',
            field=models.OneToOneField(help_text='Lecturer profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to=settings.AUTH_USER_MODEL),
        ),
    ]
