# Generated by Django 3.2.5 on 2021-10-22 04:22

from django.db import migrations, models
import faculty.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='icon',
            field=models.ImageField(blank=True, help_text='Faculty icon', null=True, upload_to=faculty.models.upload_picture_to),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='picture',
            field=models.ImageField(blank=True, help_text='Picture of the faculty building, student , etc.', null=True, upload_to=faculty.models.upload_picture_to),
        ),
    ]
