# Generated by Django 3.2.5 on 2021-10-22 04:35

import CollegeManagementSystem.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20211022_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=120, unique=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
    ]
