# Generated by Django 3.2.5 on 2021-10-22 05:47

from django.db import migrations, models
import faculty.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='icon',
            field=models.ImageField(default=None, help_text='Faculty icon', upload_to=faculty.models.upload_picture_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='picture',
            field=models.ImageField(default=None, help_text='Picture of the faculty building, student , etc.', upload_to=faculty.models.upload_picture_to),
            preserve_default=False,
        ),
    ]
