# Generated by Django 3.2.5 on 2021-10-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_alter_faculty_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
