# Generated by Django 3.2.5 on 2021-10-30 19:51

import CollegeManagementSystem.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_faculty_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(help_text='Name of Faculty,College, or School', max_length=120, unique=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
    ]
