# Generated by Django 3.2.5 on 2021-10-22 04:35

import CollegeManagementSystem.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211019_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='last name and other names', max_length=120, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
    ]
