# Generated by Django 3.2.9 on 2021-11-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211022_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
