# Generated by Django 3.2.9 on 2021-11-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='session_id',
            new_name='session_key',
        ),
    ]
