# Generated by Django 3.2.9 on 2021-12-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211130_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name', 'email'), 'permissions': [('add_lecturerprofile', 'Add Lecturer Profile')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
