# Generated by Django 3.2.9 on 2021-12-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name', 'email'), 'permissions': [('add_lecturerprofile', 'Add Lecturer Profile'), ('set_password4other', 'Set password for other user')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
