# Generated by Django 4.0 on 2022-02-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name', 'email'), 'permissions': [('add_lecturerprofile', 'Add Lecturer Profile'), ('set_password4other', 'Set password for other user'), ('self_change_password', 'Can user change his or her password')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
