# Generated by Django 4.0.2 on 2022-03-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_username_user_computer_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name', 'email'), 'permissions': [('can_view_profile', 'Can view their profile'), ('add_lecturerprofile', 'Add Lecturer Profile'), ('view_lecturerprofile', 'Can View Lecturer Profile'), ('set_password4other', 'Set password for other user'), ('self_change_password', 'Can user change his or her password')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
