# Generated by Django 3.2.5 on 2021-10-20 21:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_history', models.BooleanField(help_text='Do you have employment history')),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('specific_duty', ckeditor.fields.RichTextField(blank=True, help_text='Specific duties', null=True)),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=120, null=True)),
                ('employed_from', models.DateField(blank=True, null=True)),
                ('employed_to', models.DateField(blank=True, null=True)),
                ('why_leave', models.CharField(blank=True, help_text='Reason for leaving employment', max_length=120, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Employment Histories',
                'db_table': 'employmentHistory',
            },
        ),
    ]
