# Generated by Django 3.2.5 on 2021-10-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empoymentHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistorymodel',
            name='has_history',
            field=models.BooleanField(help_text='Do you have employment history', null=True),
        ),
    ]
