# Generated by Django 3.2.5 on 2021-10-20 08:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empoymentHistory', '0002_alter_employmenthistorymodel_has_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistorymodel',
            name='has_history',
            field=models.BooleanField(help_text='If you have no employment history uncheck this *.', null=True, verbose_name='Do you have employment history'),
        ),
        migrations.AlterField(
            model_name='employmenthistorymodel',
            name='specific_duty',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Specific duties'),
        ),
    ]
