# Generated by Django 3.2.9 on 2021-11-28 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empoymentHistory', '0004_alter_employmenthistorymodel_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistorymodel',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
