# Generated by Django 3.2.9 on 2021-12-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empoymentHistory', '0005_alter_employmenthistorymodel_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistorymodel',
            name='company_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Institution'),
        ),
    ]
