# Generated by Django 3.2.5 on 2021-10-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_alter_department_short_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('department', models.ForeignKey(help_text="programmes's department", on_delete=django.db.models.deletion.CASCADE, related_name='department', to='department.department')),
            ],
        ),
    ]
