# Generated by Django 3.2.5 on 2021-10-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ('name', 'id')},
        ),
        migrations.AlterModelTable(
            name='programme',
            table='programme',
        ),
    ]
