# Generated by Django 3.2.9 on 2021-11-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_alter_programme_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='programme',
            order_with_respect_to='department',
        ),
    ]
