# Generated by Django 3.2.9 on 2021-11-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_auto_20211124_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='max_student',
            field=models.IntegerField(help_text='The maximum student this programme can take for a particular level', null=True),
        ),
    ]
