# Generated by Django 3.2.9 on 2021-12-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_programme_max_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'permissions': [('list_programme', 'can view programme list')]},
        ),
    ]
