# Generated by Django 3.2.5 on 2021-10-15 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(help_text='Country or Nationality', max_length=2)),
                ('region', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('home_town', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('current_region', models.CharField(max_length=120)),
                ('current_latitude', models.CharField(blank=True, max_length=60, null=True)),
                ('current_longitude', models.CharField(blank=True, max_length=60, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
