# Generated by Django 3.2.5 on 2021-10-22 04:35

import CollegeManagementSystem.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20211019_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='current_region',
            field=models.CharField(max_length=120, null=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=120, null=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
        migrations.AlterField(
            model_name='address',
            name='home_town',
            field=models.CharField(max_length=120, null=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=120, null=True, validators=[CollegeManagementSystem.validation.validate_alphanumberic_space]),
        ),
    ]
