# Generated by Django 3.2.5 on 2021-10-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_alter_programme_name'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('id', 'profile'), 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='programme_choices',
            field=models.ManyToManyField(help_text='student programme choices', limit_choices_to=3, related_name='programme_choices', to='programme.Programme'),
        ),
    ]
