# Generated by Django 3.2.5 on 2021-10-30 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme', '0003_alter_programme_name'),
        ('student', '0002_auto_20211028_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='programme_choices',
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', related_query_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentProgrammeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_choice', to='programme.programme')),
                ('second_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_choice', to='programme.programme')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('third_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_choice', to='programme.programme')),
            ],
            options={
                'db_table': 'studentprogrammechoice',
            },
        ),
    ]
