# Generated by Django 3.2.5 on 2021-10-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_alter_programme_name'),
        ('student', '0003_auto_20211030_1951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprogrammechoice',
            unique_together={('first_choice', 'second_choice', 'student')},
        ),
    ]
