# Generated by Django 3.2.5 on 2021-10-30 21:30

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprogrammechoice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_picture', models.FileField(help_text='Include all the necessary(WASSCE, NOV/DEC, HND, SRN, Diploma Cert, etc) certificate in one pdf file', upload_to=student.models.upload_certificate_copy_to)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', related_query_name='student', to='student.student')),
            ],
            options={
                'db_table': 'student_admission_exam_certificate',
            },
        ),
        migrations.CreateModel(
            name='CertExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('index_number', models.CharField(help_text='Examination number', max_length=30)),
                ('examination_year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)])),
                ('school', models.CharField(help_text='School Name', max_length=200)),
                ('Grade', models.CharField(max_length=3)),
                ('examination_type', models.CharField(choices=[('private candidate', 'Private Candidate'), ('school candidate', 'School Candidate')], default='school candidate', max_length=120)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='student.admissioncertificate')),
            ],
            options={
                'db_table': 'student_admission_exam_result',
            },
        ),
    ]
