# Generated by Django 3.2.5 on 2021-10-31 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_certexamrecord_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certexamrecord',
            old_name='Grade',
            new_name='grade',
        ),
    ]
