# Generated by Django 3.2.5 on 2021-10-31 02:50

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_certexamrecord_index_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncertificate',
            name='certificate_picture',
            field=models.FileField(help_text='Include all the necessary(WASSCE, NOV/DEC, HND, SRN, Diploma Cert, etc) certificate in one pdf file', null=True, upload_to=student.models.upload_certificate_copy_to),
        ),
    ]
