# Generated by Django 3.2.5 on 2021-10-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_admissioncertificate_certificate_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certexamrecord',
            unique_together={('certificate', 'examination_type', 'examination_year', 'subject')},
        ),
    ]
