# Generated by Django 3.2.5 on 2021-11-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20211104_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', related_query_name='certificate_records', to='student.admissioncertificate'),
        ),
    ]
