# Generated by Django 3.2.9 on 2021-11-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_certexamrecord_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_records', related_query_name='certificate_records', to='student.admissioncertificate'),
        ),
    ]
