# Generated by Django 3.2.9 on 2021-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_studentpreviouseducation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='index_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
