# Generated by Django 3.2.9 on 2021-11-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student_index_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('B2', 'B2'), ('C', 'C'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('D', 'D'), ('E8', 'E8'), ('F9', 'F9')], max_length=3),
        ),
    ]
