# Generated by Django 3.2.9 on 2021-11-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_programme_max_student'),
        ('student', '0020_alter_certexamrecord_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programme.programme'),
        ),
    ]
