# Generated by Django 3.2.9 on 2021-11-28 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_auto_20211122_1414'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0021_student_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_admission_form', to='admission.studentforms'),
        ),
        migrations.AlterField(
            model_name='student',
            name='index_number',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', related_query_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
