# Generated by Django 3.2.9 on 2021-11-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_student_admission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_date',
            new_name='date_admitted',
        ),
    ]
