# Generated by Django 3.2.9 on 2021-12-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_rename_admission_date_student_date_admitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('id', 'profile'), 'permissions': [('list_student', 'can view student list')], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
