# Generated by Django 3.2.9 on 2021-12-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_student_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is this student current or active'),
        ),
    ]
