# Generated by Django 3.2.9 on 2021-12-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_admitted',
            field=models.DateField(help_text='Date student was admitted', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_completed',
            field=models.DateField(blank=True, help_text='Student completion date', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='index_number',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
