# Generated by Django 4.0 on 2022-02-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_alter_certexamrecord_examination_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Literature in English', 'Literature in English'), ('Dangme', 'Dangme'), ('Auto Mechanics', 'Auto Mechanics'), ('Building Construction', 'Building Construction'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Basketry', 'Basketry'), ('Arabic', 'Arabic'), ('Any one or two of the following', 'Any one or two of the following'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('History', 'History'), ('Ga', 'Ga'), ('Sculpture', 'Sculpture'), ('Nzema', 'Nzema'), ('Financial Accounting', 'Financial Accounting'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Economics', 'Economics'), ('French', 'French'), ('Biology', 'Biology'), ('Forestry', 'Forestry'), ('Picture Making', 'Picture Making'), ('Ewe', 'Ewe'), ('Woodwork', 'Woodwork'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Applied Electricity', 'Applied Electricity'), ('Metalwork', 'Metalwork'), ('Languages', 'Languages'), ('Chemistry', 'Chemistry'), ('Fisheries', 'Fisheries'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Textiles', 'Textiles'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Gonja', 'Gonja'), ('General Agriculture', 'General Agriculture'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Dagaare', 'Dagaare'), ('French or Music', 'French or Music'), ('ICT (Elective)', 'ICT (Elective)'), ('Literature-in English', 'Literature-in English'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Technical Drawing', 'Technical Drawing'), ('English Language', 'English Language'), ('Animal Husbandry', 'Animal Husbandry'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Social Studies', 'Social Studies'), ('Government', 'Government'), ('Leatherwork', 'Leatherwork'), ('Jewellery', 'Jewellery'), ('Dagbani', 'Dagbani'), ('Integrated Science', 'Integrated Science'), ('Management-In-Living', 'Management-In-Living'), ('Music', 'Music'), ('Kasem', 'Kasem'), ('Physics', 'Physics'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Geography', 'Geography'), ('Business Management', 'Business Management'), ('Graphic Design', 'Graphic Design'), ('Electronics', 'Electronics'), ('Twi (Asante)', 'Twi (Asante)'), ('Ceramics', 'Ceramics'), ('French OR Music', 'French OR Music'), ('Clothing and Textiles', 'Clothing and Textiles')], max_length=120),
        ),
    ]
