# Generated by Django 4.0 on 2022-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Textiles', 'Textiles'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Financial Accounting', 'Financial Accounting'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Graphic Design', 'Graphic Design'), ('Ga', 'Ga'), ('ICT (Elective)', 'ICT (Elective)'), ('History', 'History'), ('Gonja', 'Gonja'), ('French', 'French'), ('Chemistry', 'Chemistry'), ('Animal Husbandry', 'Animal Husbandry'), ('Building Construction', 'Building Construction'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Kasem', 'Kasem'), ('Literature-in English', 'Literature-in English'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Arabic', 'Arabic'), ('Picture Making', 'Picture Making'), ('Music', 'Music'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Fisheries', 'Fisheries'), ('Forestry', 'Forestry'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Any one or two of the following', 'Any one or two of the following'), ('Auto Mechanics', 'Auto Mechanics'), ('Dagaare', 'Dagaare'), ('Dagbani', 'Dagbani'), ('Applied Electricity', 'Applied Electricity'), ('French or Music', 'French or Music'), ('Integrated Science', 'Integrated Science'), ('Electronics', 'Electronics'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Geography', 'Geography'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Woodwork', 'Woodwork'), ('Leatherwork', 'Leatherwork'), ('General Agriculture', 'General Agriculture'), ('Economics', 'Economics'), ('Business Management', 'Business Management'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Technical Drawing', 'Technical Drawing'), ('Twi (Asante)', 'Twi (Asante)'), ('French OR Music', 'French OR Music'), ('Metalwork', 'Metalwork'), ('Languages', 'Languages'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Social Studies', 'Social Studies'), ('Biology', 'Biology'), ('Sculpture', 'Sculpture'), ('Government', 'Government'), ('English Language', 'English Language'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Management-In-Living', 'Management-In-Living'), ('Literature in English', 'Literature in English'), ('Jewellery', 'Jewellery'), ('Dangme', 'Dangme'), ('Ewe', 'Ewe'), ('Nzema', 'Nzema'), ('Basketry', 'Basketry'), ('Physics', 'Physics'), ('Ceramics', 'Ceramics')], max_length=120),
        ),
    ]
