# Generated by Django 4.0 on 2022-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Basketry', 'Basketry'), ('Integrated Science', 'Integrated Science'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Applied Electricity', 'Applied Electricity'), ('Dagaare', 'Dagaare'), ('Biology', 'Biology'), ('Languages', 'Languages'), ('Management-In-Living', 'Management-In-Living'), ('Picture Making', 'Picture Making'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Literature in English', 'Literature in English'), ('Sculpture', 'Sculpture'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Metalwork', 'Metalwork'), ('French or Music', 'French or Music'), ('English Language', 'English Language'), ('Government', 'Government'), ('Economics', 'Economics'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Music', 'Music'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Jewellery', 'Jewellery'), ('Electronics', 'Electronics'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Chemistry', 'Chemistry'), ('French', 'French'), ('Any one or two of the following', 'Any one or two of the following'), ('Forestry', 'Forestry'), ('Auto Mechanics', 'Auto Mechanics'), ('Woodwork', 'Woodwork'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Dangme', 'Dangme'), ('Building Construction', 'Building Construction'), ('Business Management', 'Business Management'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Textiles', 'Textiles'), ('Ga', 'Ga'), ('Twi (Asante)', 'Twi (Asante)'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Fisheries', 'Fisheries'), ('Social Studies', 'Social Studies'), ('Ceramics', 'Ceramics'), ('History', 'History'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Dagbani', 'Dagbani'), ('Arabic', 'Arabic'), ('Geography', 'Geography'), ('ICT (Elective)', 'ICT (Elective)'), ('Financial Accounting', 'Financial Accounting'), ('Ewe', 'Ewe'), ('Physics', 'Physics'), ('General Agriculture', 'General Agriculture'), ('Mathematics (Core)', 'Mathematics (Core)'), ('French OR Music', 'French OR Music'), ('Literature-in English', 'Literature-in English'), ('Animal Husbandry', 'Animal Husbandry'), ('Graphic Design', 'Graphic Design'), ('Gonja', 'Gonja'), ('Nzema', 'Nzema'), ('Leatherwork', 'Leatherwork'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Technical Drawing', 'Technical Drawing'), ('Kasem', 'Kasem')], max_length=120),
        ),
    ]
