# Generated by Django 4.0 on 2022-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Basketry', 'Basketry'), ('Languages', 'Languages'), ('Biology', 'Biology'), ('Nzema', 'Nzema'), ('Technical Drawing', 'Technical Drawing'), ('ICT (Elective)', 'ICT (Elective)'), ('Chemistry', 'Chemistry'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Twi (Asante)', 'Twi (Asante)'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Financial Accounting', 'Financial Accounting'), ('Gonja', 'Gonja'), ('Ewe', 'Ewe'), ('Geography', 'Geography'), ('Dangme', 'Dangme'), ('Physics', 'Physics'), ('Business Management', 'Business Management'), ('Forestry', 'Forestry'), ('Dagbani', 'Dagbani'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Integrated Science', 'Integrated Science'), ('Textiles', 'Textiles'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Animal Husbandry', 'Animal Husbandry'), ('Sculpture', 'Sculpture'), ('Any one or two of the following', 'Any one or two of the following'), ('Music', 'Music'), ('Management-In-Living', 'Management-In-Living'), ('Auto Mechanics', 'Auto Mechanics'), ('Arabic', 'Arabic'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Jewellery', 'Jewellery'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('History', 'History'), ('Literature in English', 'Literature in English'), ('Applied Electricity', 'Applied Electricity'), ('French or Music', 'French or Music'), ('French', 'French'), ('Economics', 'Economics'), ('Electronics', 'Electronics'), ('Literature-in English', 'Literature-in English'), ('Ga', 'Ga'), ('Fisheries', 'Fisheries'), ('Ceramics', 'Ceramics'), ('English Language', 'English Language'), ('Building Construction', 'Building Construction'), ('Kasem', 'Kasem'), ('Graphic Design', 'Graphic Design'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Picture Making', 'Picture Making'), ('Clerical Office Duties', 'Clerical Office Duties'), ('General Agriculture', 'General Agriculture'), ('Metalwork', 'Metalwork'), ('Dagaare', 'Dagaare'), ('Woodwork', 'Woodwork'), ('Leatherwork', 'Leatherwork'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Social Studies', 'Social Studies'), ('French OR Music', 'French OR Music'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Government', 'Government'), ('General Knowledge-In-Art', 'General Knowledge-In-Art')], max_length=120),
        ),
    ]
