# Generated by Django 4.0 on 2022-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Mathematics (Core)', 'Mathematics (Core)'), ('Twi (Asante)', 'Twi (Asante)'), ('ICT (Elective)', 'ICT (Elective)'), ('Basketry', 'Basketry'), ('Picture Making', 'Picture Making'), ('Dangme', 'Dangme'), ('Financial Accounting', 'Financial Accounting'), ('Management-In-Living', 'Management-In-Living'), ('Music', 'Music'), ('Leatherwork', 'Leatherwork'), ('Ga', 'Ga'), ('Forestry', 'Forestry'), ('French OR Music', 'French OR Music'), ('Ceramics', 'Ceramics'), ('Graphic Design', 'Graphic Design'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('French or Music', 'French or Music'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Government', 'Government'), ('Gonja', 'Gonja'), ('French', 'French'), ('Integrated Science', 'Integrated Science'), ('Arabic', 'Arabic'), ('Literature-in English', 'Literature-in English'), ('Auto Mechanics', 'Auto Mechanics'), ('Chemistry', 'Chemistry'), ('Electronics', 'Electronics'), ('Jewellery', 'Jewellery'), ('General Agriculture', 'General Agriculture'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Business Management', 'Business Management'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Textiles', 'Textiles'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Social Studies', 'Social Studies'), ('Economics', 'Economics'), ('Sculpture', 'Sculpture'), ('Nzema', 'Nzema'), ('Literature in English', 'Literature in English'), ('Dagaare', 'Dagaare'), ('Building Construction', 'Building Construction'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('History', 'History'), ('Languages', 'Languages'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Fisheries', 'Fisheries'), ('Animal Husbandry', 'Animal Husbandry'), ('Dagbani', 'Dagbani'), ('Geography', 'Geography'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Metalwork', 'Metalwork'), ('Biology', 'Biology'), ('Kasem', 'Kasem'), ('Ewe', 'Ewe'), ('Foods and Nutrition', 'Foods and Nutrition'), ('English Language', 'English Language'), ('Any one or two of the following', 'Any one or two of the following'), ('Applied Electricity', 'Applied Electricity'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Woodwork', 'Woodwork'), ('Technical Drawing', 'Technical Drawing'), ('Physics', 'Physics'), ('General Knowledge-In-Art', 'General Knowledge-In-Art')], max_length=120),
        ),
    ]
