# Generated by Django 4.0.2 on 2022-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Literature in English', 'Literature in English'), ('Biology', 'Biology'), ('Any one or two of the following', 'Any one or two of the following'), ('Ga', 'Ga'), ('Technical Drawing', 'Technical Drawing'), ('Physics', 'Physics'), ('Applied Electricity', 'Applied Electricity'), ('Forestry', 'Forestry'), ('Social Studies', 'Social Studies'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Textiles', 'Textiles'), ('General Agriculture', 'General Agriculture'), ('French or Music', 'French or Music'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Dangme', 'Dangme'), ('Gonja', 'Gonja'), ('Kasem', 'Kasem'), ('Fisheries', 'Fisheries'), ('Economics', 'Economics'), ('Geography', 'Geography'), ('Electronics', 'Electronics'), ('Picture Making', 'Picture Making'), ('Basketry', 'Basketry'), ('Animal Husbandry', 'Animal Husbandry'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Dagaare', 'Dagaare'), ('Jewellery', 'Jewellery'), ('Nzema', 'Nzema'), ('Languages', 'Languages'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Metalwork', 'Metalwork'), ('Leatherwork', 'Leatherwork'), ('Literature-in English', 'Literature-in English'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Building Construction', 'Building Construction'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('French', 'French'), ('Integrated Science', 'Integrated Science'), ('French OR Music', 'French OR Music'), ('English Language', 'English Language'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Auto Mechanics', 'Auto Mechanics'), ('Woodwork', 'Woodwork'), ('Chemistry', 'Chemistry'), ('ICT (Elective)', 'ICT (Elective)'), ('Music', 'Music'), ('Government', 'Government'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Sculpture', 'Sculpture'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Ewe', 'Ewe'), ('Graphic Design', 'Graphic Design'), ('Business Management', 'Business Management'), ('Arabic', 'Arabic'), ('Financial Accounting', 'Financial Accounting'), ('Twi (Asante)', 'Twi (Asante)'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Ceramics', 'Ceramics'), ('Dagbani', 'Dagbani'), ('History', 'History'), ('Management-In-Living', 'Management-In-Living')], max_length=120),
        ),
    ]
