# Generated by Django 4.0.2 on 2022-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('ICT (Elective)', 'ICT (Elective)'), ('Literature in English', 'Literature in English'), ('English Language', 'English Language'), ('Business Management', 'Business Management'), ('Twi (Asante)', 'Twi (Asante)'), ('Dagbani', 'Dagbani'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Leatherwork', 'Leatherwork'), ('Animal Husbandry', 'Animal Husbandry'), ('Auto Mechanics', 'Auto Mechanics'), ('Jewellery', 'Jewellery'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Chemistry', 'Chemistry'), ('Ceramics', 'Ceramics'), ('Geography', 'Geography'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Basketry', 'Basketry'), ('Kasem', 'Kasem'), ('Financial Accounting', 'Financial Accounting'), ('Dangme', 'Dangme'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('History', 'History'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Ewe', 'Ewe'), ('Picture Making', 'Picture Making'), ('Music', 'Music'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Ga', 'Ga'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('French OR Music', 'French OR Music'), ('Forestry', 'Forestry'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Gonja', 'Gonja'), ('Management-In-Living', 'Management-In-Living'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Nzema', 'Nzema'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Physics', 'Physics'), ('Economics', 'Economics'), ('Literature-in English', 'Literature-in English'), ('Fisheries', 'Fisheries'), ('Any one or two of the following', 'Any one or two of the following'), ('Electronics', 'Electronics'), ('French', 'French'), ('Biology', 'Biology'), ('French or Music', 'French or Music'), ('General Agriculture', 'General Agriculture'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Textiles', 'Textiles'), ('Dagaare', 'Dagaare'), ('Sculpture', 'Sculpture'), ('Languages', 'Languages'), ('Arabic', 'Arabic'), ('Woodwork', 'Woodwork'), ('Building Construction', 'Building Construction'), ('Integrated Science', 'Integrated Science'), ('Government', 'Government'), ('Graphic Design', 'Graphic Design'), ('Applied Electricity', 'Applied Electricity'), ('Technical Drawing', 'Technical Drawing'), ('Metalwork', 'Metalwork'), ('Social Studies', 'Social Studies')], max_length=120),
        ),
    ]
