# Generated by Django 4.0.2 on 2022-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Biology', 'Biology'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Arabic', 'Arabic'), ('Leatherwork', 'Leatherwork'), ('Animal Husbandry', 'Animal Husbandry'), ('French', 'French'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Forestry', 'Forestry'), ('Languages', 'Languages'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Twi (Asante)', 'Twi (Asante)'), ('History', 'History'), ('Economics', 'Economics'), ('Fisheries', 'Fisheries'), ('Ewe', 'Ewe'), ('Technical Drawing', 'Technical Drawing'), ('Social Studies', 'Social Studies'), ('Music', 'Music'), ('Ga', 'Ga'), ('Integrated Science', 'Integrated Science'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Financial Accounting', 'Financial Accounting'), ('French OR Music', 'French OR Music'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Nzema', 'Nzema'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Ceramics', 'Ceramics'), ('Business Management', 'Business Management'), ('English Language', 'English Language'), ('Woodwork', 'Woodwork'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Jewellery', 'Jewellery'), ('Picture Making', 'Picture Making'), ('Literature-in English', 'Literature-in English'), ('Gonja', 'Gonja'), ('Auto Mechanics', 'Auto Mechanics'), ('Literature in English', 'Literature in English'), ('French or Music', 'French or Music'), ('Dangme', 'Dangme'), ('Electronics', 'Electronics'), ('ICT (Elective)', 'ICT (Elective)'), ('Chemistry', 'Chemistry'), ('Sculpture', 'Sculpture'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Dagbani', 'Dagbani'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Building Construction', 'Building Construction'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Basketry', 'Basketry'), ('Dagaare', 'Dagaare'), ('Textiles', 'Textiles'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Geography', 'Geography'), ('Applied Electricity', 'Applied Electricity'), ('Management-In-Living', 'Management-In-Living'), ('Kasem', 'Kasem'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('General Agriculture', 'General Agriculture'), ('Metalwork', 'Metalwork'), ('Graphic Design', 'Graphic Design'), ('Any one or two of the following', 'Any one or two of the following'), ('Physics', 'Physics'), ('Government', 'Government')], max_length=120),
        ),
    ]
