# Generated by Django 4.0.2 on 2022-03-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Dagbani', 'Dagbani'), ('French or Music', 'French or Music'), ('Picture Making', 'Picture Making'), ('Chemistry', 'Chemistry'), ('Dangme', 'Dangme'), ('ICT (Elective)', 'ICT (Elective)'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('English Language', 'English Language'), ('Economics', 'Economics'), ('Forestry', 'Forestry'), ('Graphic Design', 'Graphic Design'), ('Sculpture', 'Sculpture'), ('Technical Drawing', 'Technical Drawing'), ('Gonja', 'Gonja'), ('Jewellery', 'Jewellery'), ('Geography', 'Geography'), ('Auto Mechanics', 'Auto Mechanics'), ('Ceramics', 'Ceramics'), ('Metalwork', 'Metalwork'), ('Building Construction', 'Building Construction'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Literature in English', 'Literature in English'), ('Languages', 'Languages'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Textiles', 'Textiles'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Any one or two of the following', 'Any one or two of the following'), ('Management-In-Living', 'Management-In-Living'), ('Integrated Science', 'Integrated Science'), ('General Agriculture', 'General Agriculture'), ('Animal Husbandry', 'Animal Husbandry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Music', 'Music'), ('French OR Music', 'French OR Music'), ('Applied Electricity', 'Applied Electricity'), ('Mathematics (Core)', 'Mathematics (Core)'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Ewe', 'Ewe'), ('Basketry', 'Basketry'), ('Twi (Asante)', 'Twi (Asante)'), ('Fisheries', 'Fisheries'), ('Kasem', 'Kasem'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Electronics', 'Electronics'), ('Arabic', 'Arabic'), ('French', 'French'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Ga', 'Ga'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Social Studies', 'Social Studies'), ('Leatherwork', 'Leatherwork'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Foods and Nutrition', 'Foods and Nutrition'), ('History', 'History'), ('Dagaare', 'Dagaare'), ('Business Management', 'Business Management'), ('Woodwork', 'Woodwork'), ('Literature-in English', 'Literature-in English'), ('Government', 'Government'), ('Nzema', 'Nzema'), ('Financial Accounting', 'Financial Accounting'), ('West Africa Traditional Religion', 'West Africa Traditional Religion')], max_length=120),
        ),
    ]
