# Generated by Django 4.0.2 on 2022-03-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Gonja', 'Gonja'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Jewellery', 'Jewellery'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Financial Accounting', 'Financial Accounting'), ('Economics', 'Economics'), ('Picture Making', 'Picture Making'), ('Ga', 'Ga'), ('Dagaare', 'Dagaare'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Arabic', 'Arabic'), ('Biology', 'Biology'), ('Dangme', 'Dangme'), ('Sculpture', 'Sculpture'), ('French OR Music', 'French OR Music'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Integrated Science', 'Integrated Science'), ('Building Construction', 'Building Construction'), ('Fisheries', 'Fisheries'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Auto Mechanics', 'Auto Mechanics'), ('Physics', 'Physics'), ('Literature-in English', 'Literature-in English'), ('Business Management', 'Business Management'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Dagbani', 'Dagbani'), ('Ewe', 'Ewe'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Basketry', 'Basketry'), ('Textiles', 'Textiles'), ('Technical Drawing', 'Technical Drawing'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Chemistry', 'Chemistry'), ('Forestry', 'Forestry'), ('Electronics', 'Electronics'), ('French', 'French'), ('Languages', 'Languages'), ('Twi (Asante)', 'Twi (Asante)'), ('Leatherwork', 'Leatherwork'), ('Literature in English', 'Literature in English'), ('Government', 'Government'), ('Management-In-Living', 'Management-In-Living'), ('Metalwork', 'Metalwork'), ('French or Music', 'French or Music'), ('Woodwork', 'Woodwork'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Kasem', 'Kasem'), ('Any one or two of the following', 'Any one or two of the following'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Geography', 'Geography'), ('Ceramics', 'Ceramics'), ('Animal Husbandry', 'Animal Husbandry'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('General Agriculture', 'General Agriculture'), ('English Language', 'English Language'), ('Graphic Design', 'Graphic Design'), ('ICT (Elective)', 'ICT (Elective)'), ('Applied Electricity', 'Applied Electricity'), ('History', 'History'), ('Music', 'Music'), ('Nzema', 'Nzema'), ('Social Studies', 'Social Studies')], max_length=120),
        ),
    ]
