# Generated by Django 4.0.2 on 2022-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Dangme', 'Dangme'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Woodwork', 'Woodwork'), ('History', 'History'), ('Literature in English', 'Literature in English'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Chemistry', 'Chemistry'), ('Gonja', 'Gonja'), ('Ceramics', 'Ceramics'), ('Languages', 'Languages'), ('Leatherwork', 'Leatherwork'), ('Arabic', 'Arabic'), ('General Agriculture', 'General Agriculture'), ('Biology', 'Biology'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Electronics', 'Electronics'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Building Construction', 'Building Construction'), ('Animal Husbandry', 'Animal Husbandry'), ('Dagbani', 'Dagbani'), ('Music', 'Music'), ('English Language', 'English Language'), ('Sculpture', 'Sculpture'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Auto Mechanics', 'Auto Mechanics'), ('Financial Accounting', 'Financial Accounting'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Twi (Asante)', 'Twi (Asante)'), ('Government', 'Government'), ('Fisheries', 'Fisheries'), ('Ga', 'Ga'), ('French', 'French'), ('Forestry', 'Forestry'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Physics', 'Physics'), ('French or Music', 'French or Music'), ('Economics', 'Economics'), ('Graphic Design', 'Graphic Design'), ('Social Studies', 'Social Studies'), ('Technical Drawing', 'Technical Drawing'), ('Management-In-Living', 'Management-In-Living'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('French OR Music', 'French OR Music'), ('Picture Making', 'Picture Making'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Nzema', 'Nzema'), ('Basketry', 'Basketry'), ('Jewellery', 'Jewellery'), ('Literature-in English', 'Literature-in English'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Any one or two of the following', 'Any one or two of the following'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Ewe', 'Ewe'), ('Metalwork', 'Metalwork'), ('Applied Electricity', 'Applied Electricity'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Integrated Science', 'Integrated Science'), ('Geography', 'Geography'), ('Kasem', 'Kasem'), ('Textiles', 'Textiles'), ('Dagaare', 'Dagaare'), ('Business Management', 'Business Management'), ('ICT (Elective)', 'ICT (Elective)')], max_length=120),
        ),
    ]
