# Generated by Django 4.0.2 on 2022-03-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Forestry', 'Forestry'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Dagaare', 'Dagaare'), ('Applied Electricity', 'Applied Electricity'), ('Biology', 'Biology'), ('Integrated Science', 'Integrated Science'), ('Picture Making', 'Picture Making'), ('Kasem', 'Kasem'), ('French or Music', 'French or Music'), ('Financial Accounting', 'Financial Accounting'), ('Basketry', 'Basketry'), ('Electronics', 'Electronics'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Fisheries', 'Fisheries'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('French OR Music', 'French OR Music'), ('History', 'History'), ('Business Management', 'Business Management'), ('Technical Drawing', 'Technical Drawing'), ('Woodwork', 'Woodwork'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Animal Husbandry', 'Animal Husbandry'), ('Ewe', 'Ewe'), ('Physics', 'Physics'), ('Sculpture', 'Sculpture'), ('French', 'French'), ('Auto Mechanics', 'Auto Mechanics'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Textiles', 'Textiles'), ('ICT (Elective)', 'ICT (Elective)'), ('Ga', 'Ga'), ('Graphic Design', 'Graphic Design'), ('General Agriculture', 'General Agriculture'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Arabic', 'Arabic'), ('Metalwork', 'Metalwork'), ('Government', 'Government'), ('Building Construction', 'Building Construction'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Literature in English', 'Literature in English'), ('Languages', 'Languages'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Literature-in English', 'Literature-in English'), ('Economics', 'Economics'), ('Music', 'Music'), ('Nzema', 'Nzema'), ('Dagbani', 'Dagbani'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Leatherwork', 'Leatherwork'), ('Dangme', 'Dangme'), ('Geography', 'Geography'), ('Management-In-Living', 'Management-In-Living'), ('Ceramics', 'Ceramics'), ('Gonja', 'Gonja'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Social Studies', 'Social Studies'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Jewellery', 'Jewellery'), ('Any one or two of the following', 'Any one or two of the following'), ('Chemistry', 'Chemistry'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Twi (Asante)', 'Twi (Asante)'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('English Language', 'English Language')], max_length=120),
        ),
    ]
