# Generated by Django 4.0.2 on 2022-03-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Government', 'Government'), ('Any one or two of the following', 'Any one or two of the following'), ('Geography', 'Geography'), ('Forestry', 'Forestry'), ('Kasem', 'Kasem'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Ewe', 'Ewe'), ('Ga', 'Ga'), ('Graphic Design', 'Graphic Design'), ('English Language', 'English Language'), ('Applied Electricity', 'Applied Electricity'), ('Physics', 'Physics'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Basketry', 'Basketry'), ('Financial Accounting', 'Financial Accounting'), ('Technical Drawing', 'Technical Drawing'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Literature in English', 'Literature in English'), ('Economics', 'Economics'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('French or Music', 'French or Music'), ('Christian Religious Studies', 'Christian Religious Studies'), ('French', 'French'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Ceramics', 'Ceramics'), ('Picture Making', 'Picture Making'), ('Literature-in English', 'Literature-in English'), ('Nzema', 'Nzema'), ('Management-In-Living', 'Management-In-Living'), ('Woodwork', 'Woodwork'), ('Sculpture', 'Sculpture'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('General Agriculture', 'General Agriculture'), ('Arabic', 'Arabic'), ('Animal Husbandry', 'Animal Husbandry'), ('Biology', 'Biology'), ('Dangme', 'Dangme'), ('Building Construction', 'Building Construction'), ('Metalwork', 'Metalwork'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Gonja', 'Gonja'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('French OR Music', 'French OR Music'), ('Dagaare', 'Dagaare'), ('Textiles', 'Textiles'), ('Leatherwork', 'Leatherwork'), ('Electronics', 'Electronics'), ('Social Studies', 'Social Studies'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Auto Mechanics', 'Auto Mechanics'), ('History', 'History'), ('Dagbani', 'Dagbani'), ('Chemistry', 'Chemistry'), ('Integrated Science', 'Integrated Science'), ('Business Management', 'Business Management'), ('Music', 'Music'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Languages', 'Languages'), ('Fisheries', 'Fisheries'), ('Jewellery', 'Jewellery'), ('ICT (Elective)', 'ICT (Elective)'), ('Twi (Asante)', 'Twi (Asante)')], max_length=120),
        ),
    ]
