# Generated by Django 4.0.2 on 2022-03-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0053_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Christian Religious Studies', 'Christian Religious Studies'), ('ICT (Elective)', 'ICT (Elective)'), ('Biology', 'Biology'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Financial Accounting', 'Financial Accounting'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Arabic', 'Arabic'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Management-In-Living', 'Management-In-Living'), ('Technical Drawing', 'Technical Drawing'), ('Leatherwork', 'Leatherwork'), ('Textiles', 'Textiles'), ('Fisheries', 'Fisheries'), ('Business Management', 'Business Management'), ('Jewellery', 'Jewellery'), ('Sculpture', 'Sculpture'), ('French', 'French'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Languages', 'Languages'), ('Dangme', 'Dangme'), ('Any one or two of the following', 'Any one or two of the following'), ('Social Studies', 'Social Studies'), ('Ga', 'Ga'), ('English Language', 'English Language'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Applied Electricity', 'Applied Electricity'), ('Economics', 'Economics'), ('Ceramics', 'Ceramics'), ('Literature in English', 'Literature in English'), ('Woodwork', 'Woodwork'), ('Kasem', 'Kasem'), ('General Agriculture', 'General Agriculture'), ('Metalwork', 'Metalwork'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Picture Making', 'Picture Making'), ('Twi (Asante)', 'Twi (Asante)'), ('Physics', 'Physics'), ('Graphic Design', 'Graphic Design'), ('History', 'History'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Nzema', 'Nzema'), ('Electronics', 'Electronics'), ('Animal Husbandry', 'Animal Husbandry'), ('Basketry', 'Basketry'), ('Literature-in English', 'Literature-in English'), ('Geography', 'Geography'), ('Dagaare', 'Dagaare'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Forestry', 'Forestry'), ('Auto Mechanics', 'Auto Mechanics'), ('Dagbani', 'Dagbani'), ('Gonja', 'Gonja'), ('Ewe', 'Ewe'), ('Integrated Science', 'Integrated Science'), ('Chemistry', 'Chemistry'), ('Government', 'Government'), ('Building Construction', 'Building Construction'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Mathematics (Core)', 'Mathematics (Core)'), ('French or Music', 'French or Music'), ('Music', 'Music'), ('French OR Music', 'French OR Music')], max_length=120),
        ),
    ]
