# Generated by Django 4.0.2 on 2022-03-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0054_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('Nzema', 'Nzema'), ('Any one or two of the following', 'Any one or two of the following'), ('Metalwork', 'Metalwork'), ('Forestry', 'Forestry'), ('Business Management', 'Business Management'), ('Arabic', 'Arabic'), ('Languages', 'Languages'), ('Dangme', 'Dangme'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Dagaare', 'Dagaare'), ('Leatherwork', 'Leatherwork'), ('Social Studies', 'Social Studies'), ('Jewellery', 'Jewellery'), ('Electronics', 'Electronics'), ('Financial Accounting', 'Financial Accounting'), ('Literature-in English', 'Literature-in English'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Ceramics', 'Ceramics'), ('Sculpture', 'Sculpture'), ('Technical Drawing', 'Technical Drawing'), ('Physics', 'Physics'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Ewe', 'Ewe'), ('Gonja', 'Gonja'), ('French', 'French'), ('Kasem', 'Kasem'), ('Building Construction', 'Building Construction'), ('Geography', 'Geography'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Biology', 'Biology'), ('French OR Music', 'French OR Music'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Auto Mechanics', 'Auto Mechanics'), ('Woodwork', 'Woodwork'), ('History', 'History'), ('Chemistry', 'Chemistry'), ('Fisheries', 'Fisheries'), ('Economics', 'Economics'), ('ICT (Elective)', 'ICT (Elective)'), ('Animal Husbandry', 'Animal Husbandry'), ('Integrated Science', 'Integrated Science'), ('Basketry', 'Basketry'), ('Music', 'Music'), ('Dagbani', 'Dagbani'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('English Language', 'English Language'), ('Literature in English', 'Literature in English'), ('Applied Electricity', 'Applied Electricity'), ('Textiles', 'Textiles'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Twi (Asante)', 'Twi (Asante)'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('General Agriculture', 'General Agriculture'), ('Government', 'Government'), ('Picture Making', 'Picture Making'), ('Management-In-Living', 'Management-In-Living'), ('Ga', 'Ga'), ('French or Music', 'French or Music')], max_length=120),
        ),
    ]
