# Generated by Django 4.0.2 on 2022-03-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0055_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Clerical Office Duties', 'Clerical Office Duties'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Integrated Science', 'Integrated Science'), ('Languages', 'Languages'), ('Leatherwork', 'Leatherwork'), ('Nzema', 'Nzema'), ('Mathematics (Core)', 'Mathematics (Core)'), ('French or Music', 'French or Music'), ('Ga', 'Ga'), ('Animal Husbandry', 'Animal Husbandry'), ('Ceramics', 'Ceramics'), ('Auto Mechanics', 'Auto Mechanics'), ('Sculpture', 'Sculpture'), ('Literature-in English', 'Literature-in English'), ('Physics', 'Physics'), ('Dagbani', 'Dagbani'), ('Management-In-Living', 'Management-In-Living'), ('Fisheries', 'Fisheries'), ('Applied Electricity', 'Applied Electricity'), ('Building Construction', 'Building Construction'), ('Basketry', 'Basketry'), ('Gonja', 'Gonja'), ('General Agriculture', 'General Agriculture'), ('Forestry', 'Forestry'), ('Arabic', 'Arabic'), ('Ewe', 'Ewe'), ('Financial Accounting', 'Financial Accounting'), ('Technical Drawing', 'Technical Drawing'), ('Dangme', 'Dangme'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('English Language', 'English Language'), ('Government', 'Government'), ('Christian Religious Studies', 'Christian Religious Studies'), ('ICT (Elective)', 'ICT (Elective)'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Twi (Asante)', 'Twi (Asante)'), ('French OR Music', 'French OR Music'), ('Jewellery', 'Jewellery'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Textiles', 'Textiles'), ('Literature in English', 'Literature in English'), ('Geography', 'Geography'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Biology', 'Biology'), ('French', 'French'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Dagaare', 'Dagaare'), ('Kasem', 'Kasem'), ('Electronics', 'Electronics'), ('Metalwork', 'Metalwork'), ('Economics', 'Economics'), ('Picture Making', 'Picture Making'), ('Music', 'Music'), ('Social Studies', 'Social Studies'), ('Business Management', 'Business Management'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Woodwork', 'Woodwork'), ('Graphic Design', 'Graphic Design'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Chemistry', 'Chemistry'), ('History', 'History'), ('Any one or two of the following', 'Any one or two of the following')], max_length=120),
        ),
    ]
