# Generated by Django 4.0.2 on 2022-03-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0057_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('French', 'French'), ('ICT (Elective)', 'ICT (Elective)'), ('Languages', 'Languages'), ('Fisheries', 'Fisheries'), ('Basketry', 'Basketry'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Twi (Asante)', 'Twi (Asante)'), ('Gonja', 'Gonja'), ('Management-In-Living', 'Management-In-Living'), ('Sculpture', 'Sculpture'), ('Government', 'Government'), ('Auto Mechanics', 'Auto Mechanics'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Animal Husbandry', 'Animal Husbandry'), ('General Agriculture', 'General Agriculture'), ('French or Music', 'French or Music'), ('Technical Drawing', 'Technical Drawing'), ('Dagbani', 'Dagbani'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Physics', 'Physics'), ('Metalwork', 'Metalwork'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Kasem', 'Kasem'), ('Arabic', 'Arabic'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Literature-in English', 'Literature-in English'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Nzema', 'Nzema'), ('Graphic Design', 'Graphic Design'), ('Business Management', 'Business Management'), ('Music', 'Music'), ('Geography', 'Geography'), ('Woodwork', 'Woodwork'), ('Dangme', 'Dangme'), ('Jewellery', 'Jewellery'), ('Ga', 'Ga'), ('Ceramics', 'Ceramics'), ('Social Studies', 'Social Studies'), ('Biology', 'Biology'), ('Picture Making', 'Picture Making'), ('Financial Accounting', 'Financial Accounting'), ('French OR Music', 'French OR Music'), ('Integrated Science', 'Integrated Science'), ('Forestry', 'Forestry'), ('Electronics', 'Electronics'), ('History', 'History'), ('Economics', 'Economics'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Ewe', 'Ewe'), ('Literature in English', 'Literature in English'), ('Applied Electricity', 'Applied Electricity'), ('Chemistry', 'Chemistry'), ('Building Construction', 'Building Construction'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Any one or two of the following', 'Any one or two of the following'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Textiles', 'Textiles'), ('Dagaare', 'Dagaare'), ('Leatherwork', 'Leatherwork'), ('English Language', 'English Language')], max_length=120),
        ),
    ]
