# Generated by Django 4.0.2 on 2022-03-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0059_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Woodwork', 'Woodwork'), ('Applied Electricity', 'Applied Electricity'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Social Studies', 'Social Studies'), ('Nzema', 'Nzema'), ('English Language', 'English Language'), ('Mathematics (Core)', 'Mathematics (Core)'), ('General Agriculture', 'General Agriculture'), ('Clothing and Textiles', 'Clothing and Textiles'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Chemistry', 'Chemistry'), ('Ceramics', 'Ceramics'), ('Technical Drawing', 'Technical Drawing'), ('Economics', 'Economics'), ('Auto Mechanics', 'Auto Mechanics'), ('Music', 'Music'), ('Fisheries', 'Fisheries'), ('Dangme', 'Dangme'), ('Gonja', 'Gonja'), ('Arabic', 'Arabic'), ('Textiles', 'Textiles'), ('Business Management', 'Business Management'), ('Forestry', 'Forestry'), ('Financial Accounting', 'Financial Accounting'), ('Metalwork', 'Metalwork'), ('Geography', 'Geography'), ('Basketry', 'Basketry'), ('Integrated Science', 'Integrated Science'), ('French', 'French'), ('Jewellery', 'Jewellery'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Ewe', 'Ewe'), ('Electronics', 'Electronics'), ('History', 'History'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Dagaare', 'Dagaare'), ('Kasem', 'Kasem'), ('Physics', 'Physics'), ('French OR Music', 'French OR Music'), ('French or Music', 'French or Music'), ('Twi (Asante)', 'Twi (Asante)'), ('Literature-in English', 'Literature-in English'), ('Sculpture', 'Sculpture'), ('Languages', 'Languages'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('ICT (Elective)', 'ICT (Elective)'), ('Leatherwork', 'Leatherwork'), ('Building Construction', 'Building Construction'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Ga', 'Ga'), ('Picture Making', 'Picture Making'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Dagbani', 'Dagbani'), ('Biology', 'Biology'), ('Graphic Design', 'Graphic Design'), ('Government', 'Government'), ('Animal Husbandry', 'Animal Husbandry'), ('Any one or two of the following', 'Any one or two of the following'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Literature in English', 'Literature in English'), ('Management-In-Living', 'Management-In-Living')], max_length=120),
        ),
    ]
