# Generated by Django 4.0.2 on 2022-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0060_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Clothing and Textiles', 'Clothing and Textiles'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('History', 'History'), ('Picture Making', 'Picture Making'), ('Ceramics', 'Ceramics'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Forestry', 'Forestry'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Music', 'Music'), ('Literature-in English', 'Literature-in English'), ('Applied Electricity', 'Applied Electricity'), ('Kasem', 'Kasem'), ('Jewellery', 'Jewellery'), ('French', 'French'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Building Construction', 'Building Construction'), ('Social Studies', 'Social Studies'), ('Woodwork', 'Woodwork'), ('Economics', 'Economics'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Textiles', 'Textiles'), ('Literature in English', 'Literature in English'), ('Business Management', 'Business Management'), ('Technical Drawing', 'Technical Drawing'), ('Ga', 'Ga'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Graphic Design', 'Graphic Design'), ('Arabic', 'Arabic'), ('Dagbani', 'Dagbani'), ('Auto Mechanics', 'Auto Mechanics'), ('French or Music', 'French or Music'), ('French OR Music', 'French OR Music'), ('Geography', 'Geography'), ('Fisheries', 'Fisheries'), ('Government', 'Government'), ('Leatherwork', 'Leatherwork'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Twi (Asante)', 'Twi (Asante)'), ('Financial Accounting', 'Financial Accounting'), ('Languages', 'Languages'), ('Animal Husbandry', 'Animal Husbandry'), ('Ewe', 'Ewe'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Any one or two of the following', 'Any one or two of the following'), ('Dangme', 'Dangme'), ('Management-In-Living', 'Management-In-Living'), ('Dagaare', 'Dagaare'), ('Electronics', 'Electronics'), ('General Agriculture', 'General Agriculture'), ('Metalwork', 'Metalwork'), ('Basketry', 'Basketry'), ('Sculpture', 'Sculpture'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Nzema', 'Nzema'), ('Biology', 'Biology'), ('Integrated Science', 'Integrated Science'), ('Mathematics (Core)', 'Mathematics (Core)'), ('ICT (Elective)', 'ICT (Elective)'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('English Language', 'English Language'), ('Gonja', 'Gonja')], max_length=120),
        ),
    ]
