# Generated by Django 4.0.2 on 2022-05-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0061_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Government', 'Government'), ('French OR Music', 'French OR Music'), ('Any one or two of the following', 'Any one or two of the following'), ('Kasem', 'Kasem'), ('Financial Accounting', 'Financial Accounting'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Nzema', 'Nzema'), ('Picture Making', 'Picture Making'), ('Twi (Asante)', 'Twi (Asante)'), ('History', 'History'), ('Fisheries', 'Fisheries'), ('General Agriculture', 'General Agriculture'), ('Languages', 'Languages'), ('Ewe', 'Ewe'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Literature in English', 'Literature in English'), ('Arabic', 'Arabic'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('French', 'French'), ('Jewellery', 'Jewellery'), ('ICT (Elective)', 'ICT (Elective)'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Leatherwork', 'Leatherwork'), ('Metalwork', 'Metalwork'), ('Geography', 'Geography'), ('Music', 'Music'), ('Dangme', 'Dangme'), ('Electronics', 'Electronics'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Gonja', 'Gonja'), ('Graphic Design', 'Graphic Design'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Economics', 'Economics'), ('Textiles', 'Textiles'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Technical Drawing', 'Technical Drawing'), ('Dagaare', 'Dagaare'), ('Ceramics', 'Ceramics'), ('Sculpture', 'Sculpture'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Business Management', 'Business Management'), ('Integrated Science', 'Integrated Science'), ('Applied Electricity', 'Applied Electricity'), ('Ga', 'Ga'), ('Social Studies', 'Social Studies'), ('Woodwork', 'Woodwork'), ('Biology', 'Biology'), ('Literature-in English', 'Literature-in English'), ('Chemistry', 'Chemistry'), ('Auto Mechanics', 'Auto Mechanics'), ('Dagbani', 'Dagbani'), ('Building Construction', 'Building Construction'), ('Management-In-Living', 'Management-In-Living'), ('Forestry', 'Forestry'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Basketry', 'Basketry'), ('Animal Husbandry', 'Animal Husbandry'), ('Physics', 'Physics'), ('French or Music', 'French or Music'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('English Language', 'English Language')], max_length=120),
        ),
    ]
