# Generated by Django 4.1 on 2022-08-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0063_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Geography', 'Geography'), ('Applied Electricity', 'Applied Electricity'), ('Auto Mechanics', 'Auto Mechanics'), ('Chemistry', 'Chemistry'), ('Management-In-Living', 'Management-In-Living'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Any one or two of the following', 'Any one or two of the following'), ('Ga', 'Ga'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Ewe', 'Ewe'), ('ICT (Elective)', 'ICT (Elective)'), ('Animal Husbandry', 'Animal Husbandry'), ('Jewellery', 'Jewellery'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Nzema', 'Nzema'), ('Metalwork', 'Metalwork'), ('Integrated Science', 'Integrated Science'), ('Financial Accounting', 'Financial Accounting'), ('Textiles', 'Textiles'), ('Literature-in English', 'Literature-in English'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Literature in English', 'Literature in English'), ('French', 'French'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Arabic', 'Arabic'), ('Electronics', 'Electronics'), ('Kasem', 'Kasem'), ('Social Studies', 'Social Studies'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Dangme', 'Dangme'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Leatherwork', 'Leatherwork'), ('Music', 'Music'), ('Government', 'Government'), ('Building Construction', 'Building Construction'), ('Forestry', 'Forestry'), ('Graphic Design', 'Graphic Design'), ('French OR Music', 'French OR Music'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Dagaare', 'Dagaare'), ('English Language', 'English Language'), ('Woodwork', 'Woodwork'), ('Sculpture', 'Sculpture'), ('Languages', 'Languages'), ('Physics', 'Physics'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Biology', 'Biology'), ('Economics', 'Economics'), ('Ceramics', 'Ceramics'), ('Fisheries', 'Fisheries'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Technical Drawing', 'Technical Drawing'), ('Gonja', 'Gonja'), ('History', 'History'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Basketry', 'Basketry'), ('Dagbani', 'Dagbani'), ('Picture Making', 'Picture Making'), ('Business Management', 'Business Management'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('General Agriculture', 'General Agriculture'), ('French or Music', 'French or Music'), ('Twi (Asante)', 'Twi (Asante)')], max_length=120),
        ),
    ]
