# Generated by Django 4.1 on 2022-08-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0064_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_graduate',
            field=models.BooleanField(default=False, help_text='Is the student a graduate'),
        ),
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Metalwork', 'Metalwork'), ('Music', 'Music'), ('Dagaare', 'Dagaare'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Mathematics (Core)', 'Mathematics (Core)'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Auto Mechanics', 'Auto Mechanics'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('History', 'History'), ('Jewellery', 'Jewellery'), ('Biology', 'Biology'), ('Dangme', 'Dangme'), ('French or Music', 'French or Music'), ('Ceramics', 'Ceramics'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Financial Accounting', 'Financial Accounting'), ('Chemistry', 'Chemistry'), ('French', 'French'), ('Technical Drawing', 'Technical Drawing'), ('Sculpture', 'Sculpture'), ('Literature in English', 'Literature in English'), ('Government', 'Government'), ('Physics', 'Physics'), ('Integrated Science', 'Integrated Science'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Basketry', 'Basketry'), ('ICT (Elective)', 'ICT (Elective)'), ('Management-In-Living', 'Management-In-Living'), ('Social Studies', 'Social Studies'), ('Geography', 'Geography'), ('Textiles', 'Textiles'), ('Fisheries', 'Fisheries'), ('Gonja', 'Gonja'), ('Electronics', 'Electronics'), ('Any one or two of the following', 'Any one or two of the following'), ('Arabic', 'Arabic'), ('Building Construction', 'Building Construction'), ('Picture Making', 'Picture Making'), ('Literature-in English', 'Literature-in English'), ('Economics', 'Economics'), ('Forestry', 'Forestry'), ('Dagbani', 'Dagbani'), ('Ga', 'Ga'), ('Languages', 'Languages'), ('Ewe', 'Ewe'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Business Management', 'Business Management'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('French OR Music', 'French OR Music'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Graphic Design', 'Graphic Design'), ('Kasem', 'Kasem'), ('Woodwork', 'Woodwork'), ('Twi (Asante)', 'Twi (Asante)'), ('Animal Husbandry', 'Animal Husbandry'), ('English Language', 'English Language'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Applied Electricity', 'Applied Electricity'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Nzema', 'Nzema'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Leatherwork', 'Leatherwork'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('General Agriculture', 'General Agriculture')], max_length=120),
        ),
    ]
