# Generated by Django 4.1 on 2022-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0065_student_has_graduate_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Music', 'Music'), ('French or Music', 'French or Music'), ('Integrated Science', 'Integrated Science'), ('Ewe', 'Ewe'), ('Business Management', 'Business Management'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Leatherwork', 'Leatherwork'), ('Dagbani', 'Dagbani'), ('General Agriculture', 'General Agriculture'), ('Gonja', 'Gonja'), ('Forestry', 'Forestry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Dagaare', 'Dagaare'), ('Building Construction', 'Building Construction'), ('Dangme', 'Dangme'), ('Basketry', 'Basketry'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('Picture Making', 'Picture Making'), ('Sculpture', 'Sculpture'), ('ICT (Elective)', 'ICT (Elective)'), ('Textiles', 'Textiles'), ('Ceramics', 'Ceramics'), ('Electronics', 'Electronics'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Animal Husbandry', 'Animal Husbandry'), ('Arabic', 'Arabic'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Chemistry', 'Chemistry'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Mathematics (Core)', 'Mathematics (Core)'), ('English Language', 'English Language'), ('Clerical Office Duties', 'Clerical Office Duties'), ('Applied Electricity', 'Applied Electricity'), ('Economics', 'Economics'), ('Metalwork', 'Metalwork'), ('Woodwork', 'Woodwork'), ('Graphic Design', 'Graphic Design'), ('Geography', 'Geography'), ('Twi (Asante)', 'Twi (Asante)'), ('Ga', 'Ga'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('Management-In-Living', 'Management-In-Living'), ('Technical Drawing', 'Technical Drawing'), ('French OR Music', 'French OR Music'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Nzema', 'Nzema'), ('Kasem', 'Kasem'), ('Languages', 'Languages'), ('French', 'French'), ('Social Studies', 'Social Studies'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Auto Mechanics', 'Auto Mechanics'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Any one or two of the following', 'Any one or two of the following'), ('Literature-in English', 'Literature-in English'), ('Fisheries', 'Fisheries'), ('Jewellery', 'Jewellery'), ('History', 'History'), ('Government', 'Government'), ('Literature in English', 'Literature in English'), ('Financial Accounting', 'Financial Accounting')], max_length=120),
        ),
    ]
