# Generated by Django 4.1 on 2022-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0066_alter_certexamrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certexamrecord',
            name='subject',
            field=models.CharField(choices=[('Social Studies', 'Social Studies'), ('Literature in English', 'Literature in English'), ('Principles of Cost Accounting', 'Principles of Cost Accounting'), ('Clerical Office Duties', 'Clerical Office Duties'), ('General Agriculture', 'General Agriculture'), ('French', 'French'), ('Literature-in English', 'Literature-in English'), ('Music', 'Music'), ('Twi (Akuapem)', 'Twi (Akuapem)'), ('Mathematics (Elective)', 'Mathematics (Elective)'), ('Crop Husbandry and Horticulture', 'Crop Husbandry and Horticulture'), ('Geography', 'Geography'), ('Applied Electricity', 'Applied Electricity'), ('Foods and Nutrition', 'Foods and Nutrition'), ('Basketry', 'Basketry'), ('General Knowledge-In-Art', 'General Knowledge-In-Art'), ('Forestry', 'Forestry'), ('Government', 'Government'), ('Mathematics (Core)', 'Mathematics (Core)'), ('History', 'History'), ('Nzema', 'Nzema'), ('Auto Mechanics', 'Auto Mechanics'), ('Christian Religious Studies', 'Christian Religious Studies'), ('Leatherwork', 'Leatherwork'), ('Ewe', 'Ewe'), ('Ga', 'Ga'), ('Chemistry', 'Chemistry'), ('Financial Accounting', 'Financial Accounting'), ('Fisheries', 'Fisheries'), ('Languages', 'Languages'), ('Technical Drawing', 'Technical Drawing'), ('Islamic Religious Studies', 'Islamic Religious Studies'), ('English Language', 'English Language'), ('Metalwork', 'Metalwork'), ('Building Construction', 'Building Construction'), ('Clothing and Textiles', 'Clothing and Textiles'), ('Ceramics', 'Ceramics'), ('Dangme', 'Dangme'), ('Kasem', 'Kasem'), ('Animal Husbandry', 'Animal Husbandry'), ('Textiles', 'Textiles'), ('Woodwork', 'Woodwork'), ('Dagaare', 'Dagaare'), ('Economics', 'Economics'), ('Graphic Design', 'Graphic Design'), ('West Africa Traditional Religion', 'West Africa Traditional Religion'), ('French OR Music', 'French OR Music'), ('French or Music', 'French or Music'), ('Management-In-Living', 'Management-In-Living'), ('Twi (Asante)', 'Twi (Asante)'), ('Biology', 'Biology'), ('Business Management', 'Business Management'), ('Picture Making', 'Picture Making'), ('Arabic', 'Arabic'), ('Dagbani', 'Dagbani'), ('Any one or two of the following', 'Any one or two of the following'), ('ICT (Elective)', 'ICT (Elective)'), ('Integrated Science', 'Integrated Science'), ('Gonja', 'Gonja'), ('Typewriting (40wpm)', 'Typewriting (40wpm)'), ('Physics', 'Physics'), ('Jewellery', 'Jewellery'), ('Sculpture', 'Sculpture'), ('Electronics', 'Electronics')], max_length=120),
        ),
    ]
