# Generated by Django 3.2.5 on 2021-10-23 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0005_alter_faculty_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the department.', max_length=120, unique=True)),
                ('short_form', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, help_text="Department's faculty", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
            },
        ),
    ]
