# Generated by Django 3.2.5 on 2021-10-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_form',
            field=models.CharField(blank=True, help_text='Department Abbreviation. Short name/form', max_length=30, null=True, unique=True, verbose_name='Short name'),
        ),
    ]
