# Generated by Django 3.2.5 on 2021-10-27 16:07

import department.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_short_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=department.models.upload_picture_to),
        ),
    ]
