# Generated by Django 3.2.9 on 2021-12-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('list_department', 'can view departments list')], 'verbose_name': 'department', 'verbose_name_plural': 'Departments'},
        ),
    ]
